name: tamawith
description: "졸작1"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  camera: ^0.11.0
  web_socket_channel: ^3.0.3
  model_viewer_plus: ^1.10.0
  google_generative_ai: ^0.4.0
  ar_flutter_plugin_2: ^0.0.1
  vector_math: ^2.1.4
  sqflite: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/TAMAwith_LOGO.jpg"
  min_sdk_android: 21 # android min sdk documentation

flutter:
  uses-material-design: true

  # 이미지 설정
  assets:
    - assets/images/
    - assets/backs/
    - assets/images/tama_back.png
    - assets/images/tama_bored.png
    - assets/images/tama_clean.png
    - assets/images/tama_eat.png
    - assets/images/tama_happy.png
    - assets/images/icon_camera.png
    - assets/logo/
    - assets/models/
    - assets/models/TAMA1_stop.glb
    - assets/models/TAMA1_Casual_Walk.glb
    - assets/models/TAMA1_Big_Wave_Hello.glb
    - assets/models/TAMA1_Skip_Forward.glb
    - assets/models/TAMA1_Wave_One_Hand.glb
    - assets/models/tama1.glb

  # 폰트 설정
  fonts:
    - family: MyCustomFont
      fonts:
        - asset: assets/fonts/memomentkkukkukk.otf